import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

import { storeGeneratedFile } from './storage.js';

let directory: string | undefined;

afterEach(() => {
  if (directory) rmSync(directory, { recursive: true, force: true });
  directory = undefined;
});

describe('storeGeneratedFile', () => {
  it('stores generated bytes privately under a random UUID key with a digest', async () => {
    directory = mkdtempSync(join(tmpdir(), 'swiftclaim-generated-'));
    const bytes = Buffer.from('generated protocol document');

    const stored = await storeGeneratedFile(directory, bytes);
    const path = join(directory, `${stored.storageKey}.blob`);

    expect(stored.storageKey).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
    );
    expect(stored.sizeBytes).toBe(bytes.length);
    expect(stored.sha256).toBe(
      createHash('sha256').update(bytes).digest('hex'),
    );
    expect(readFileSync(path)).toEqual(bytes);
    expect(statSync(path).mode & 0o777).toBe(0o600);
  });
});
