import { AlertTriangle, BadgeCheck, CalendarClock, FileSearch, UserRound } from 'lucide-react';

import type { ProtocolWorkspace } from '../../api.js';

const label = (value: string) => value.replaceAll('_', ' ').replace(/^./, (character) => character.toUpperCase());
const money = (minor: number | null, currency: string) => minor === null ? 'Not agreed' : new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(minor / 100);

interface Props { workspace: ProtocolWorkspace; onAction: (action: 'select_route' | 'create_expert' | 'update_expert' | 'record_conflict' | 'approve_instruction' | 'record_milestone' | 'record_report' | 'record_question' | 'record_answer') => void; }

export function ExpertEvidenceView({ workspace, onAction }: Props) {
  const expert = workspace.experts[0];
  return <div className="protocol-view">
    <header className="protocol-view__header"><div><span className="eyebrow">Independent evidence</span><h3>Experts</h3><p>Route, identity, conflicts, instructions and reports are separately governed.</p></div>{workspace.permissions.canPrepare ? <button className="button button--secondary button--small" type="button" onClick={() => onAction('select_route')}>Review expert route</button> : null}</header>
    <section className="protocol-route-banner"><div><span className="eyebrow">Selected route</span><strong>{label(workspace.case.expertRoute)}</strong><p>{workspace.case.expertRouteReason || 'No route reason recorded.'}</p></div>{workspace.permissions.canPrepare && !expert ? <button className="button button--primary button--small" type="button" onClick={() => onAction('create_expert')}>Add expert</button> : null}</section>
    {!expert ? <div className="protocol-empty"><UserRound size={28} /><strong>No expert engagement</strong><p>Select the controlled route before recording the proposed expert.</p></div> : <>
      <section className="expert-profile-card"><span className="expert-profile-card__avatar"><UserRound size={24} /></span><div className="expert-profile-card__identity"><span className="eyebrow">{label(expert.expertRole)}</span><h4>{expert.expertName}</h4><p>{expert.organisation || 'Independent expert'} · {expert.qualifications || 'Qualifications not supplied'}</p></div><span className={expert.verificationStatus === 'user_verified' ? 'provenance-chip provenance-chip--confirmed' : 'provenance-chip provenance-chip--warning'}>{expert.verificationStatus === 'user_verified' ? <BadgeCheck size={14} /> : <AlertTriangle size={14} />}{label(expert.verificationStatus)}</span></section>
      <div className="expert-stat-grid"><article><span>Terms</span><strong>{label(expert.termsStatus)}</strong><small>{expert.feeBasis || 'Basis not recorded'}</small>{workspace.permissions.canPrepare ? <button className="text-button" type="button" onClick={() => onAction('update_expert')}>Update terms</button> : null}</article><article><span>Agreed fee</span><strong>{money(expert.feeMinor, expert.currency)}</strong><small>{expert.payerSplit.claimantPercent}% claimant · {expert.payerSplit.landlordPercent}% landlord</small></article><article><span>Report target</span><strong>{expert.targetReportOn ?? 'Not set'}</strong><small>{label(expert.state)}</small></article></div>
      <div className="protocol-fact-grid"><section className="protocol-section"><div className="protocol-section__heading"><div><span className="eyebrow">Conflict control</span><h4>Latest check</h4></div>{workspace.permissions.canApprove || workspace.permissions.canOverrideConflict ? <button className="button button--ghost button--small" type="button" onClick={() => onAction('record_conflict')}>Record check</button> : null}</div>{expert.conflictChecks[0] ? <dl className="protocol-dl"><div><dt>Outcome</dt><dd>{label(expert.conflictChecks[0].outcome)}</dd></div><div><dt>Decision</dt><dd>{label(expert.conflictChecks[0].decision)}</dd></div><div><dt>Reason</dt><dd>{expert.conflictChecks[0].reason}</dd></div></dl> : <p className="protocol-missing">Missing</p>}</section><section className="protocol-section"><div className="protocol-section__heading"><div><span className="eyebrow">Instruction</span><h4>Approved versions</h4></div>{workspace.permissions.canApprove ? <button className="button button--ghost button--small" type="button" onClick={() => onAction('approve_instruction')}>Approve instruction</button> : null}</div>{expert.instructionVersions.length ? <p>{expert.instructionVersions.length} immutable instruction version(s).</p> : <p className="protocol-missing">Missing</p>}</section></div>
      <section className="protocol-section"><div className="protocol-section__heading"><div><span className="eyebrow">Expert chronology</span><h4>Milestones</h4></div>{workspace.permissions.canPrepare ? <button className="button button--primary button--small" type="button" onClick={() => onAction('record_milestone')}>Record expert event</button> : null}</div>{expert.milestones.length ? <div className="expert-timeline">{expert.milestones.map((milestone) => <article key={milestone.id}><span><CalendarClock size={15} /></span><div><strong>{label(milestone.eventType)}</strong><p>{milestone.detail}</p><time>{milestone.occurredAt}</time></div></article>)}</div> : <p className="protocol-empty-copy">No append-only expert events.</p>}</section>
      <section className="protocol-section"><div className="protocol-section__heading"><div><span className="eyebrow">Report evidence</span><h4>Received reports</h4></div><div className="button-row">{workspace.permissions.canPrepare ? <button className="button button--secondary button--small" type="button" onClick={() => onAction('record_report')}>Record report</button> : null}{workspace.permissions.canApprove && expert.reports.length ? <button className="button button--ghost button--small" type="button" onClick={() => onAction('record_question')}>Ask question</button> : null}{workspace.permissions.canPrepare && expert.questions.length ? <button className="button button--ghost button--small" type="button" onClick={() => onAction('record_answer')}>Record answer</button> : null}</div></div>{expert.reports.length ? <div className="protocol-version-list">{expert.reports.map((report) => <article key={report.id}><FileSearch size={19} /><div><strong>{label(report.reportType)}</strong><small>Received {report.receivedOn} · {report.reviewed ? 'Reviewed' : 'Review pending'}</small></div></article>)}</div> : <div className="protocol-empty protocol-empty--compact"><FileSearch size={22} /><strong>Report missing</strong><p>No expert report document has been recorded.</p></div>}</section>
    </>}
  </div>;
}
